from concurrent.futures import ThreadPoolExecutor, TimeoutError as FuturesTimeoutError
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from backend.app.core.config import settings
from backend.app.providers.ai.factory import AIProviderFactory, BaseLLMProvider
from backend.app.schemas.trip import CostBreakdown, DayPlan, TripRequest, TripResponse

_SYSTEM_INSTRUCTION = (
    "You are a meticulous travel planner. You always reply with a single valid JSON object "
    "and never wrap it in prose or markdown."
)


class AIOrchestrator:
    """Orchestrates AI provider selection, prompt loading, timeouts, and schema validation."""

    def __init__(self, provider_names: Optional[List[str]] = None):
        self.prompts_dir = Path(__file__).resolve().parent.parent / "prompts"
        self.provider_names = AIProviderFactory.provider_chain(provider_names)

    def _load_prompt_template(self, filename: str) -> str:
        filepath = self.prompts_dir / filename
        if not filepath.exists():
            raise FileNotFoundError(f"Prompt template file not found: {filepath}")
        with open(filepath, "r", encoding="utf-8") as f:
            return f.read()

    def generate_trip_recommendation(self, req: TripRequest) -> TripResponse:
        """Load prompt template, query AI providers in fallback order, return a validated TripResponse."""
        raw_template = self._load_prompt_template("trip_recommendation.md")
        destination = req.destination.strip() or self._fallback_destination(req.mood)
        days = max(1, min(req.days, 14))

        prompt = (
            raw_template
            .replace("{origin}", req.origin or "Your origin location")
            .replace("{destination}", destination)
            .replace("{days}", str(days))
            .replace("{mood}", req.mood)
            .replace("{budget}", str(req.budget))
            .replace("{start_date}", req.start_date or "Flexible")
            .replace("{end_date}", req.end_date or "Flexible")
        )

        # Deep mode gets a longer budget for reasoning; normal mode stays snappy.
        timeout = (
            settings.AI_REQUEST_TIMEOUT_SEC
            if req.mode == "deep"
            else max(10, settings.DEEP_MODE_TIMEOUT_SEC * 4)
        )

        response, provider_name = self._try_providers(prompt, timeout)
        if response is not None:
            plan = self.normalise_plan(response, days=days, budget=req.budget, destination=destination)
            print(f"[AIOrchestrator] Trip generated by provider '{provider_name}'.")
            return plan

        print("[AIOrchestrator] All providers failed; using deterministic fallback plan.")
        return self._generate_fallback_response(req, destination)

    def _try_providers(self, prompt: str, timeout: int) -> Tuple[Optional[Dict[str, Any]], str]:
        """Query each available provider, returning the first decodable JSON payload."""
        for provider_name in self.provider_names:
            try:
                provider = AIProviderFactory.get_provider(provider_name)
                if not provider.is_available():
                    print(f"[AIOrchestrator] Provider '{provider_name}' unavailable, skipping.")
                    continue

                with ThreadPoolExecutor(max_workers=1) as executor:
                    future = executor.submit(provider.generate_structured_json, prompt, {})
                    try:
                        payload = future.result(timeout=timeout)
                    except FuturesTimeoutError:
                        future.cancel()
                        raise TimeoutError(f"provider '{provider_name}' exceeded {timeout}s")

                # Providers return parsed JSON, but a raw string is tolerated for test doubles.
                parsed = (
                    BaseLLMProvider.parse_json_object(payload)
                    if isinstance(payload, str)
                    else payload
                )
                if isinstance(parsed, dict):
                    return parsed, provider_name
            except Exception as exc:
                print(f"[AIOrchestrator] Provider '{provider_name}' failed: {exc}")
        return None, ""

    def normalise_plan(
        self,
        data: Dict[str, Any],
        days: int,
        budget: int,
        destination: str,
    ) -> TripResponse:
        """Coerce a loosely-shaped model payload into a valid TripResponse."""
        payload: Dict[str, Any] = dict(data)

        # Some models wrap the plan; unwrap before validating.
        for wrapper_key in ("revised_plan", "trip", "plan", "itinerary"):
            inner = payload.get(wrapper_key)
            if isinstance(inner, dict) and "title" in inner:
                payload = inner
                break

        payload.setdefault("destination", destination)
        payload["daily_plan"] = self._normalise_daily_plan(payload.get("daily_plan"), days, destination)

        for list_key in ("highlights", "cozy_tips", "must_try_food"):
            value = payload.get(list_key)
            if isinstance(value, str):
                payload[list_key] = [value]
            elif not isinstance(value, list):
                payload[list_key] = []

        payload["estimated_cost_breakdown"] = self._normalise_cost(
            payload.get("estimated_cost_breakdown"), budget
        )

        for field in ("title", "tagline", "summary", "best_time"):
            if not isinstance(payload.get(field), str) or not payload[field].strip():
                payload[field] = self._placeholder_text(field, destination)

        return TripResponse(**payload)

    def _normalise_daily_plan(self, plan: Any, days: int, destination: str) -> List[Dict[str, Any]]:
        """Ensure exactly `days` well-formed day blocks exist, in order."""
        entries = [entry for entry in plan if isinstance(entry, dict)] if isinstance(plan, list) else []

        by_day: Dict[int, Dict[str, Any]] = {}
        for entry in entries:
            try:
                day_number = int(entry.get("day", 0))
            except (TypeError, ValueError):
                day_number = 0
            by_day.setdefault(day_number, entry)

        normalised: List[Dict[str, Any]] = []
        for index in range(1, days + 1):
            source = by_day.get(index) or (entries[index - 1] if index - 1 < len(entries) else {})
            block: Dict[str, Any] = {"day": index}
            block["title"] = self._as_text(source.get("title"), f"Day {index} in {destination}")
            for slot in ("morning", "midday", "afternoon", "evening", "tip"):
                block[slot] = self._as_text(source.get(slot), self._placeholder_slot(slot, index, destination))
            normalised.append(block)
        return normalised

    def _normalise_cost(self, cost: Any, budget: int) -> Dict[str, int]:
        fields = ("accommodation", "food", "transport", "activities", "misc")
        defaults = {"accommodation": 0.40, "food": 0.25, "transport": 0.15, "activities": 0.12}
        result: Dict[str, int] = {}
        for field in fields:
            raw = cost.get(field) if isinstance(cost, dict) else None
            try:
                value = int(round(float(raw)))
            except (TypeError, ValueError):
                value = int(budget * defaults.get(field, 0.0)) if field in defaults else 0
            result[field] = max(0, value)

        # Reabsorb any drift into misc so the total always matches the budget exactly.
        fixed = [field for field in fields if field != "misc"]
        subtotal = sum(result[field] for field in fixed)
        if subtotal > budget:
            # Categories alone exceed the budget: scale them down proportionally
            # rather than reporting a total the traveller never agreed to.
            scale = budget / subtotal
            for field in fixed:
                result[field] = int(result[field] * scale)
            subtotal = sum(result[field] for field in fixed)
        result["misc"] = max(0, budget - subtotal)
        return result

    @staticmethod
    def _as_text(value: Any, fallback: str) -> str:
        if isinstance(value, str) and value.strip():
            return value.strip()
        if value is None:
            return fallback
        return str(value)

    @staticmethod
    def _placeholder_slot(slot: str, index: int, destination: str) -> str:
        templates = {
            "morning": f"Morning exploration around {destination} — start slow and walk the neighbourhood.",
            "midday": f"Lunch at a well-reviewed local spot near your morning stop in {destination}.",
            "afternoon": f"Afternoon sightseeing in {destination}, keeping stops within a short walk of each other.",
            "evening": f"Evening dinner and a relaxed walk through {destination}.",
            "tip": f"Book day {index} highlights in advance and keep the route compact to save transit time.",
        }
        return templates.get(slot, f"Plan your {slot} in {destination}.")

    @staticmethod
    def _placeholder_text(field: str, destination: str) -> str:
        templates = {
            "title": f"{destination} Adventure",
            "tagline": f"Discover {destination} at your own pace.",
            "summary": f"A day-by-day plan for {destination} built around your budget and travel style.",
            "best_time": "Spring and autumn offer the most comfortable weather and lighter crowds.",
        }
        return templates.get(field, f"{destination} travel plan")

    def _fallback_destination(self, mood: str) -> str:
        mood_map = {
            "relaxed": "Bali",
            "romantic": "Paris",
            "adventure": "Queenstown",
            "nature": "Costa Rica",
            "foodie": "Tokyo",
            "luxury": "Maldives",
        }
        return mood_map.get(mood.lower(), "Bali")

    def _generate_fallback_response(self, req: TripRequest, destination: str) -> TripResponse:
        """Construct a valid TripResponse schema deterministically when AI models fail."""
        days = max(1, min(req.days, 14))
        dest_lower = destination.lower().replace(" ", "_")
        daily_plans = []
        neighborhoods = ["North Beach District", "Central Old Town", "South Bay Marina", "Heritage Market Square"]
        for d in range(1, days + 1):
            district = neighborhoods[(d - 1) % len(neighborhoods)]
            daily_plans.append(DayPlan(
                day=d,
                title=f"Day {d}: Exploring {destination} ({district})",
                morning=f"Morning walk through {district} & breakfast at local artisan cafe in {destination}.",
                midday=f"Lunch at top-rated regional eatery near {district} landmark square.",
                afternoon=f"Guided tour of {district} heritage sights and scenic viewpoint (Place ID: plc_{dest_lower}_{d}).",
                evening=f"Dinner at seaside restaurant in {district} overlooking {destination}.",
                tip=f"All Day {d} sights are clustered within 1.5 km in {district} to eliminate unnecessary cross-city travel."
            ))

        acc = int(req.budget * 0.40)
        food = int(req.budget * 0.25)
        transport = int(req.budget * 0.15)
        activities = int(req.budget * 0.12)
        misc = req.budget - (acc + food + transport + activities)

        return TripResponse(
            destination=destination,
            title=f"{req.mood} {destination} Getaway",
            tagline=f"Experience the essence of {destination}.",
            summary=f"A curated {days}-day {req.mood.lower()} trip to {destination} tailored to a budget of ₹{req.budget:,} INR.",
            best_time="Spring and Autumn for mild weather and optimal sightseeing.",
            highlights=[f"Iconic views of {destination}", "Authentic local dining", "Cultural exploration"],
            daily_plan=daily_plans,
            cozy_tips=["Keep offline maps saved", "Pack comfortable walking shoes", "Stay hydrated"],
            must_try_food=[f"Traditional {destination} regional specialty", "Local artisan dessert"],
            estimated_cost_breakdown=CostBreakdown(
                accommodation=acc,
                food=food,
                transport=transport,
                activities=activities,
                misc=max(0, misc)
            )
        )
