import asyncio
import json
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from backend.app.providers.ai.factory import AIProviderFactory, BaseLLMProvider
from backend.app.schemas.trip import PlanRevisionRequest, PlanRevisionResponse, TripResponse
from backend.app.repositories.trip_repository import TripRepository
from backend.app.services.ai_orchestrator import AIOrchestrator


class TripRevisionService:
    """Business logic service for trip revision requests."""

    def __init__(self, repository: Optional[TripRepository] = None):
        self.repository = repository or TripRepository()
        self.prompts_dir = Path(__file__).resolve().parent.parent / "prompts"
        self.provider_names = AIProviderFactory.provider_chain()

    def _load_prompt_template(self) -> str:
        filepath = self.prompts_dir / "trip_revision.md"
        if not filepath.exists():
            raise FileNotFoundError(f"Revision prompt template not found: {filepath}")
        with open(filepath, "r", encoding="utf-8") as f:
            return f.read()

    async def revise_trip(self, req: PlanRevisionRequest) -> PlanRevisionResponse:
        """Revise an existing trip itinerary based on user natural language instruction."""
        if len(req.instruction.strip()) < 3:
            raise ValueError("Revision instruction must be at least 3 characters long.")

        template = self._load_prompt_template()
        pref = req.preferences
        curr = req.current_plan
        dest = curr.destination or pref.destination or "Destination"

        prompt = (
            template
            .replace("{destination}", dest)
            .replace("{days}", str(max(1, min(pref.days, 14))))
            .replace("{mood}", pref.mood)
            .replace("{budget}", str(pref.budget))
            .replace("{current_plan_json}", json.dumps(curr.model_dump(), ensure_ascii=False))
            .replace("{instruction}", req.instruction)
        )

        parsed, provider_name = await self._try_providers(prompt)
        if parsed is not None:
            try:
                res = self._build_response(parsed, req, dest)
                print(f"[TripRevisionService] Revision generated by provider '{provider_name}'.")
                self._publish_revision_event(req, res)
                return res
            except Exception as exc:
                print(f"[TripRevisionService] Provider '{provider_name}' payload rejected: {exc}")

        res = self._generate_fallback_revision(req)
        self._publish_revision_event(req, res)
        return res

    async def _try_providers(self, prompt: str) -> Tuple[Optional[Dict[str, Any]], str]:
        """Query each available provider, returning the first decodable JSON payload."""
        for provider_name in self.provider_names:
            try:
                provider = AIProviderFactory.get_provider(provider_name)
                if not provider.is_available():
                    continue
                payload = await asyncio.to_thread(
                    provider.generate_structured_json, prompt, {}
                )
                # Providers return parsed JSON; tolerate a raw string for test doubles.
                parsed = (
                    BaseLLMProvider.parse_json_object(payload)
                    if isinstance(payload, str)
                    else payload
                )
                if isinstance(parsed, dict):
                    return parsed, provider_name
            except Exception as exc:
                print(f"[TripRevisionService] Provider '{provider_name}' revision failed: {exc}")
        return None, ""

    def _build_response(
        self,
        payload: Dict[str, Any],
        req: PlanRevisionRequest,
        destination: str,
    ) -> PlanRevisionResponse:
        """Assemble a PlanRevisionResponse, tolerating wrapped or bare plan payloads."""
        target_days = max(1, min(req.preferences.days, 14))
        revised_payload = payload.get("revised_plan") if isinstance(payload.get("revised_plan"), dict) else payload
        plan = AIOrchestrator().normalise_plan(
            revised_payload, days=target_days, budget=req.preferences.budget, destination=destination
        )

        change_summary = payload.get("change_summary")
        if not isinstance(change_summary, str) or not change_summary.strip():
            change_summary = f"Incorporated traveler request: '{req.instruction}'."
        reasoning = payload.get("reasoning")
        if not isinstance(reasoning, str) or not reasoning.strip():
            reasoning = f"Adjusted daily activities and recommendations to align with instruction '{req.instruction}'."

        return PlanRevisionResponse(
            revised_plan=plan,
            change_summary=change_summary.strip(),
            reasoning=reasoning.strip(),
        )

    def _publish_revision_event(self, req: PlanRevisionRequest, res: PlanRevisionResponse) -> None:
        from backend.app.events.bus import event_bus
        from backend.app.events.domain_events import TripUpdated
        event_bus.publish(TripUpdated(
            user_id="anonymous",
            destination=res.revised_plan.destination or "Destination",
            session_id="session_active",
            instruction=req.instruction,
            aggregate_id=res.revised_plan.destination or "global"
        ))

    def _generate_fallback_revision(self, req: PlanRevisionRequest) -> PlanRevisionResponse:
        """Generate structured fallback response applying instruction adjustments."""
        revised_plan = TripResponse(**req.current_plan.model_dump())
        instr_lower = req.instruction.lower()

        if any(word in instr_lower for word in ("cheaper", "budget", "afford", "save", "less expensive")):
            original = req.current_plan.estimated_cost_breakdown
            cb = revised_plan.estimated_cost_breakdown
            reductions = {"accommodation": 0, "food": 0, "transport": 0, "activities": 0}
            for field in reductions:
                reduced = max(0, int(getattr(original, field) * 0.8))
                reductions[field] = getattr(original, field) - reduced
                setattr(cb, field, reduced)
            # Bank the savings into misc so the breakdown still sums to the original budget.
            cb.misc = max(0, original.misc + sum(reductions.values()))
            revised_plan.summary += " (Adjusted for budget-friendly preferences.)"
            change_summary = "Reduced accommodation, dining and activity costs by 20% to optimize budget."
        elif any(word in instr_lower for word in ("food", "eat", "restaurant", "culinary")):
            revised_plan.must_try_food = list(revised_plan.must_try_food) + ["Local Street Food Tasting Tour"]
            change_summary = "Added additional authentic local food experiences and culinary stops."
        elif any(word in instr_lower for word in ("day", "extend", "longer", "shorten", "fewer")):
            target = req.preferences.days
            template_days = list(req.current_plan.daily_plan)
            if target > len(template_days) and template_days:
                last = template_days[-1]
                extra = [
                    {**last.model_dump(), "day": index, "title": f"{last.title} (Part {index})"}
                    for index in range(len(template_days) + 1, target + 1)
                ]
                template_days = template_days + extra
            revised_plan.daily_plan = template_days[:target]
            change_summary = f"Adjusted the itinerary length to {target} days as requested."
        else:
            revised_plan.title = f"Revised: {revised_plan.title}"
            change_summary = f"Incorporated traveler request: '{req.instruction}'."

        return PlanRevisionResponse(
            revised_plan=revised_plan,
            change_summary=change_summary,
            reasoning=f"Adjusted daily activities and recommendations to align with instruction '{req.instruction}'."
        )
